"""
修复版本：确保Day3的Segment名称和颜色与Day1匹配
"""

import nrrd
import numpy as np
from skimage.measure import regionprops
from scipy.spatial.distance import cdist
from scipy.optimize import linear_sum_assignment
import pandas as pd
import os


def update_segment_metadata(target_header, reference_header, label_mapping):
    """
    更新目标header的segment元数据，使其与参考header匹配
    
    参数:
        target_header: 目标文件的header (将被修改)
        reference_header: 参考文件的header (Day1)
        label_mapping: {target_label: reference_label} 映射
    """
    # 删除目标文件中所有旧的Segment信息
    keys_to_delete = [key for key in target_header.keys() if key.startswith('Segment') and '_' in key]
    for key in keys_to_delete:
        del target_header[key]
    
    # 获取目标文件中的所有标签值
    # 注意：这里需要从实际数据中获取，但我们在外部函数中处理
    
    # 复制所有Segmentation相关的全局设置
    for key in reference_header.keys():
        if key.startswith('Segmentation_'):
            target_header[key] = reference_header[key]
    
    return target_header


def copy_segment_info_for_label(target_header, reference_header, target_label_value, reference_label_value):
    """
    为特定标签值复制segment信息
    
    参数:
        target_header: 目标header
        reference_header: 参考header
        target_label_value: 目标文件中的标签值
        reference_label_value: 参考文件中的标签值
    """
    # 找到参考文件中对应标签值的Segment索引
    ref_segment_idx = None
    for key in reference_header.keys():
        if key.endswith('_LabelValue'):
            if int(reference_header[key]) == reference_label_value:
                ref_segment_idx = key.split('_')[0].replace('Segment', '')
                break
    
    if ref_segment_idx is None:
        return
    
    # 找到目标文件中应该使用的Segment索引
    # 我们需要按顺序分配
    existing_segments = [key.split('_')[0] for key in target_header.keys() 
                        if key.endswith('_LabelValue')]
    if existing_segments:
        max_idx = max([int(seg.replace('Segment', '')) for seg in existing_segments])
        target_segment_idx = str(max_idx + 1)
    else:
        target_segment_idx = '0'
    
    # 复制所有segment相关的属性
    segment_keys = ['Color', 'ColorAutoGenerated', 'Extent', 'ID', 'LabelValue', 
                   'Layer', 'Name', 'NameAutoGenerated', 'Tags']
    
    for suffix in segment_keys:
        ref_key = f'Segment{ref_segment_idx}_{suffix}'
        target_key = f'Segment{target_segment_idx}_{suffix}'
        
        if ref_key in reference_header:
            value = reference_header[ref_key]
            # 如果是LabelValue，需要更新为目标标签值
            if suffix == 'LabelValue':
                target_header[target_key] = str(target_label_value)
            else:
                target_header[target_key] = value


def save_matched_segmentation(data, output_path, reference_header, label_mapping, original_header):
    """
    保存匹配后的分割，并正确设置Segment元数据
    
    参数:
        data: 匹配后的标签数据
        output_path: 输出路径
        reference_header: 参考文件(Day1)的header
        label_mapping: {original_label: new_label} 映射，只包含匹配成功的
        original_header: 原始文件的header（用于保留空间信息）
    """
    # 使用原始header作为基础（保留空间信息）
    new_header = original_header.copy()
    
    # 清空所有Segment信息
    keys_to_delete = [key for key in new_header.keys() if key.startswith('Segment') and '_' in key]
    for key in keys_to_delete:
        del new_header[key]
    
    # 获取数据中的所有唯一标签值
    unique_labels = np.unique(data)
    unique_labels = unique_labels[unique_labels > 0]  # 排除背景
    
    # 为每个标签创建Segment信息
    for seg_idx, label_value in enumerate(sorted(unique_labels)):
        label_value = int(label_value)
        
        # 检查这个标签是否在参考文件中存在
        ref_segment_idx = None
        for key in reference_header.keys():
            if key.endswith('_LabelValue'):
                if int(reference_header[key]) == label_value:
                    ref_segment_idx = key.split('_')[0].replace('Segment', '')
                    break
        
        if ref_segment_idx is not None:
            # 这个标签在Day1中存在，复制其信息
            segment_keys = ['Color', 'ColorAutoGenerated', 'Extent', 'ID', 'LabelValue', 
                           'Layer', 'Name', 'NameAutoGenerated', 'Tags']
            
            for suffix in segment_keys:
                ref_key = f'Segment{ref_segment_idx}_{suffix}'
                target_key = f'Segment{seg_idx}_{suffix}'
                
                if ref_key in reference_header:
                    new_header[target_key] = reference_header[ref_key]
        else:
            # 这是新增的标签，创建默认信息
            new_header[f'Segment{seg_idx}_Color'] = '0.5 0.5 0.5'
            new_header[f'Segment{seg_idx}_ColorAutoGenerated'] = '1'
            new_header[f'Segment{seg_idx}_Extent'] = f'0 {data.shape[0]-1} 0 {data.shape[1]-1} 0 {data.shape[2]-1}'
            new_header[f'Segment{seg_idx}_ID'] = f'Segment_{label_value}'
            new_header[f'Segment{seg_idx}_LabelValue'] = str(label_value)
            new_header[f'Segment{seg_idx}_Layer'] = '0'
            new_header[f'Segment{seg_idx}_Name'] = f'Organoid_{label_value}'
            new_header[f'Segment{seg_idx}_NameAutoGenerated'] = '0'
            new_header[f'Segment{seg_idx}_Tags'] = 'TerminologyEntry:Segmentation category and type - 3D Slicer General Anatomy list~SCT^85756007^Tissue~SCT^85756007^Tissue~^^~Anatomic codes - DICOM master list~^^~^^|'
    
    # 保存
    nrrd.write(output_path, data.astype(np.int16), new_header)
    print(f"  ✓ 已保存: {output_path}")
    print(f"    - 包含 {len(unique_labels)} 个segment")
    print(f"    - 其中 {sum(1 for l in unique_labels if any(int(reference_header[k]) == l for k in reference_header.keys() if k.endswith('_LabelValue')))} 个匹配Day1")


# 测试：重新生成Day3匹配文件
if __name__ == "__main__":
    print("="*70)
    print("重新生成Day3匹配文件，修复Segment元数据")
    print("="*70)
    
    # 读取数据
    data1, header1 = nrrd.read('ID_organoid/organoid_031_tracked.nii.seg.nrrd')
    data3_matched, header3_original = nrrd.read('results/day3_matched.nrrd')
    
    # 读取匹配日志
    df_log = pd.read_csv('results/matching_log.csv')
    df_day3 = df_log[df_log['Day'] == 'Day3']
    
    # 创建映射 (只包含匹配成功的)
    label_mapping = {}
    for _, row in df_day3.iterrows():
        if row['Status'] == 'Matched':
            label_mapping[row['Original_ID']] = row['New_ID']
    
    print(f"\n匹配成功的标签: {len(label_mapping)} 个")
    print(f"映射: {dict(list(label_mapping.items())[:5])} ...")
    
    # 保存修复后的文件
    output_path = 'results/day3_matched_fixed.nrrd'
    save_matched_segmentation(data3_matched, output_path, header1, label_mapping, header3_original)
    
    # 同样处理Day2
    print("\n" + "="*70)
    print("重新生成Day2匹配文件")
    print("="*70)
    
    data2_matched, header2_original = nrrd.read('results/day2_matched.nrrd')
    df_day2 = df_log[df_log['Day'] == 'Day2']
    
    label_mapping2 = {}
    for _, row in df_day2.iterrows():
        if row['Status'] == 'Matched':
            label_mapping2[row['Original_ID']] = row['New_ID']
    
    print(f"\n匹配成功的标签: {len(label_mapping2)} 个")
    
    output_path2 = 'results/day2_matched_fixed.nrrd'
    save_matched_segmentation(data2_matched, output_path2, header1, label_mapping2, header2_original)
    
    print("\n" + "="*70)
    print("完成！")
    print("="*70)
    print("现在在Slicer中加载:")
    print("  1. results/day1_reference.nrrd")
    print("  2. results/day2_matched_fixed.nrrd")
    print("  3. results/day3_matched_fixed.nrrd")
    print("\n相同ID的类器官应该显示相同的颜色！")
    print("="*70)
