"""
重新匹配Day2，使用更大的距离阈值（因为Day2类器官体积更大）
"""

import nrrd
import numpy as np
from skimage.measure import regionprops
from scipy.spatial.distance import cdist
from scipy.optimize import linear_sum_assignment
import pandas as pd


def match_organoids_hungarian(centroids_reference, centroids_target, max_distance=150):
    """
    使用匈牙利算法进行一对一匹配
    
    参数:
        centroids_reference: Day1的质心坐标 (n, 3)
        centroids_target: 目标day的质心坐标 (m, 3)
        max_distance: 最大匹配距离（像素）
    
    返回:
        matched_pairs: [(target_idx, ref_idx, distance), ...]
        unmatched_target: [target_idx, ...]
    """
    # 计算距离矩阵
    dist_matrix = cdist(centroids_target, centroids_reference)
    
    # 创建成本矩阵：超过阈值的设为很大的值
    cost_matrix = dist_matrix.copy()
    cost_matrix[cost_matrix > max_distance] = 1e10
    
    # 使用匈牙利算法求解
    row_ind, col_ind = linear_sum_assignment(cost_matrix)
    
    # 提取有效匹配（距离在阈值内）
    matched_pairs = []
    unmatched_target = []
    
    for target_idx, ref_idx in zip(row_ind, col_ind):
        distance = dist_matrix[target_idx, ref_idx]
        if distance <= max_distance:
            matched_pairs.append((target_idx, ref_idx, distance))
        else:
            unmatched_target.append(target_idx)
    
    # 添加未参与匹配的target
    all_matched_target = set(row_ind)
    for i in range(len(centroids_target)):
        if i not in all_matched_target:
            unmatched_target.append(i)
    
    return matched_pairs, unmatched_target


def save_matched_segmentation(data, output_path, reference_header, label_mapping, original_header):
    """
    保存匹配后的分割，正确设置Segment元数据，保留空间信息
    """
    # 使用原始header作为基础（保留空间信息）
    new_header = original_header.copy()
    
    # 清空所有Segment信息
    keys_to_delete = [key for key in new_header.keys() if key.startswith('Segment') and '_' in key]
    for key in keys_to_delete:
        del new_header[key]
    
    # 获取数据中的所有唯一标签值
    unique_labels = np.unique(data)
    unique_labels = unique_labels[unique_labels > 0]
    
    # 为每个标签创建Segment信息
    for seg_idx, label_value in enumerate(sorted(unique_labels)):
        label_value = int(label_value)
        
        # 检查这个标签是否在参考文件中存在
        ref_segment_idx = None
        for key in reference_header.keys():
            if key.endswith('_LabelValue'):
                if int(reference_header[key]) == label_value:
                    ref_segment_idx = key.split('_')[0].replace('Segment', '')
                    break
        
        if ref_segment_idx is not None:
            # 这个标签在Day1中存在，复制其信息
            segment_keys = ['Color', 'ColorAutoGenerated', 'Extent', 'ID', 'LabelValue', 
                           'Layer', 'Name', 'NameAutoGenerated', 'Tags']
            
            for suffix in segment_keys:
                ref_key = f'Segment{ref_segment_idx}_{suffix}'
                target_key = f'Segment{seg_idx}_{suffix}'
                
                if ref_key in reference_header:
                    new_header[target_key] = reference_header[ref_key]
        else:
            # 这是新增的标签，创建默认信息
            new_header[f'Segment{seg_idx}_Color'] = '0.5 0.5 0.5'
            new_header[f'Segment{seg_idx}_ColorAutoGenerated'] = '1'
            new_header[f'Segment{seg_idx}_Extent'] = f'0 {data.shape[0]-1} 0 {data.shape[1]-1} 0 {data.shape[2]-1}'
            new_header[f'Segment{seg_idx}_ID'] = f'Segment_{label_value}'
            new_header[f'Segment{seg_idx}_LabelValue'] = str(label_value)
            new_header[f'Segment{seg_idx}_Layer'] = '0'
            new_header[f'Segment{seg_idx}_Name'] = f'Organoid_{label_value}'
            new_header[f'Segment{seg_idx}_NameAutoGenerated'] = '0'
            new_header[f'Segment{seg_idx}_Tags'] = 'TerminologyEntry:Segmentation category and type - 3D Slicer General Anatomy list~SCT^85756007^Tissue~SCT^85756007^Tissue~^^~Anatomic codes - DICOM master list~^^~^^|'
    
    # 保存
    nrrd.write(output_path, data.astype(np.int16), new_header)
    print(f"  ✓ 已保存: {output_path}")


if __name__ == "__main__":
    print("="*70)
    print("重新匹配Day2（使用更大的距离阈值）")
    print("="*70)
    
    # 读取数据
    print("\n读取数据...")
    data1, header1 = nrrd.read('ID_organoid/organoid_031_tracked.nii.seg.nrrd')
    data2, header2 = nrrd.read('ID_organoid/organoid_043_tracked.nii.seg.nrrd')
    
    # 提取质心
    props1 = regionprops(data1)
    props2 = regionprops(data2)
    
    centroids1 = np.array([p.centroid for p in props1])
    centroids2 = np.array([p.centroid for p in props2])
    labels1 = [p.label for p in props1]
    labels2 = [p.label for p in props2]
    
    print(f"  Day1: {len(props1)} 个类器官")
    print(f"  Day2: {len(props2)} 个类器官")
    
    # 使用更大的阈值匹配 (150像素 = 750μm)
    max_distance = 150
    print(f"\n使用距离阈值: {max_distance} 像素 (750 μm)")
    
    matched_pairs, unmatched = match_organoids_hungarian(centroids1, centroids2, max_distance)
    
    print(f"\n匹配结果:")
    print(f"  匹配成功: {len(matched_pairs)} 个")
    print(f"  新增: {len(unmatched)} 个")
    
    # 显示匹配详情
    print(f"\n前10个匹配:")
    for i, (idx2, idx1, dist) in enumerate(matched_pairs[:10]):
        orig_id2 = labels2[idx2]
        day1_id = labels1[idx1]
        print(f"  {i+1}. Day2 ID={orig_id2} → Day1 ID={day1_id}, 距离={dist:.1f}像素")
    
    if len(matched_pairs) > 10:
        print(f"  ... (还有 {len(matched_pairs)-10} 个)")
    
    # 创建新的标签数据
    data2_new = np.zeros_like(data2)
    next_new_id = max(labels1) + 1
    
    # 应用匹配
    for idx2, idx1, _ in matched_pairs:
        orig_label2 = labels2[idx2]
        new_label = labels1[idx1]
        data2_new[data2 == orig_label2] = new_label
    
    # 为新增类器官分配ID
    print(f"\n新增类器官:")
    for idx2 in unmatched:
        orig_label2 = labels2[idx2]
        data2_new[data2 == orig_label2] = next_new_id
        print(f"  Day2 原始ID={orig_label2} → 新ID={next_new_id}")
        next_new_id += 1
    
    # 保存匹配日志
    log_records = []
    for idx2, idx1, dist in matched_pairs:
        log_records.append({
            'Original_ID': labels2[idx2],
            'New_ID': labels1[idx1],
            'Status': 'Matched',
            'Distance_pixels': dist,
            'Centroid': str(tuple(np.round(centroids2[idx2], 1))),
            'Day': 'Day2'
        })
    
    for idx2 in unmatched:
        log_records.append({
            'Original_ID': labels2[idx2],
            'New_ID': labels1[-1] + 1 + unmatched.index(idx2),
            'Status': 'New',
            'Distance_pixels': np.nan,
            'Centroid': str(tuple(np.round(centroids2[idx2], 1))),
            'Day': 'Day2'
        })
    
    df_new = pd.DataFrame(log_records)
    
    # 读取现有日志并替换Day2的记录
    df_log = pd.read_csv('results/matching_log.csv')
    df_log = df_log[df_log['Day'] != 'Day2']  # 删除旧的Day2记录
    df_log = pd.concat([df_new, df_log], ignore_index=True)
    df_log.to_csv('results/matching_log_updated.csv', index=False)
    
    print(f"\n✓ 匹配日志已更新: results/matching_log_updated.csv")
    
    # 保存新的Day2文件
    output_path = 'results/day2_matched_fixed_v2.nrrd'
    save_matched_segmentation(data2_new, output_path, header1, {}, header2)
    
    print("\n" + "="*70)
    print("完成！")
    print("="*70)
    print("在Slicer中加载:")
    print("  1. results/day1_reference.nrrd")
    print("  2. results/day2_matched_fixed_v2.nrrd")
    print("  3. results/day3_matched_fixed.nrrd")
    print("\n现在Day2应该有更多的类器官匹配到Day1了！")
    print("="*70)
